name: Build, Test Performance, and Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main  # غيّرها لو بتستخدم master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'  # غيّرها حسب إصدارك

      - name: Clean old build
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web (Release)
        run: flutter build web --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # ✅ فحص أداء الموقع قبل النشر باستخدام Lighthouse
      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Run Lighthouse Performance Test
        run: |
          npx http-server build/web -p 8080 &  # تشغيل السيرفر المحلي
          sleep 5  # انتظار السيرفر
          lighthouse http://localhost:8080 \
            --only-categories=performance,accessibility,best-practices,seo \
            --chrome-flags="--headless" \
            --output=html \
            --output-path=./lighthouse-report.html
        continue-on-error: true

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ./lighthouse-report.html

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
