name: Build and Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main  # غيّرها لو بتستخدم master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'  # عدّلها لو عندك إصدار مختلف

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
